#!/bin/sh
# Container entrypoint for apps that keep SQLite on the container disk (storage.sqlite).
# 1. Restore each database from R2 (if a replica exists).
# 2. Run the app under Litestream, which streams every write back to R2 (~1s lag).
# Generated by cloudflare-app-deploy.
set -eu

APP_CMD='__APP_CMD__'
CONFIG=/app/litestream.yml
DBS='__DB_PATHS__'

mkdir -p /data

if [ -z "${R2_ACCESS_KEY_ID:-}" ] || [ -z "${R2_DB_BUCKET:-}" ]; then
  echo "[entrypoint] WARNING: R2 credentials missing - running WITHOUT persistence; data is lost on restart" >&2
  exec sh -c "$APP_CMD"
fi

for db in $DBS; do
  attempt=1
  until litestream restore -config "$CONFIG" -if-db-not-exists -if-replica-exists "$db"; do
    if [ "$attempt" -ge 5 ]; then
      # Refuse to start on an empty database: serving (and then replicating) empty data is worse than being down.
      echo "[entrypoint] restore of $db failed after $attempt attempts - exiting so the platform restarts us" >&2
      exit 1
    fi
    attempt=$((attempt + 1))
    sleep $((attempt * 3))
  done
  echo "[entrypoint] $db ready"
done

# Litestream forwards SIGTERM to the app and flushes pending WAL frames before exiting.
exec litestream replicate -config "$CONFIG" -exec "$APP_CMD"
