// Edge Worker in front of the FastAPI container.
//
// Generic on purpose: everything app-specific (port, idle timeout, instance count, region,
// allowed origins, which env vars reach the container) arrives as Worker vars generated by
// cfdeploy from cloudflare.deploy.json. Edit this file only for app-specific edge logic.

import { Container, getRandom } from "@cloudflare/containers";

interface Env {
  BACKEND: DurableObjectNamespace<Backend>;
  APP_STAGE: string;
  FRONTEND_ORIGINS: string; // comma-separated, e.g. "https://app.example.com,http://localhost:5173"
  CONTAINER_PORT: string;
  SLEEP_AFTER: string;
  INSTANCES: string;
  REGION?: string;
  CONTAINER_ENV_KEYS: string; // comma-separated names of vars/secrets forwarded into the container
  [key: string]: unknown;
}

// The library waits 20s for the port by default. Cold starts (image pull + Python imports +
// SQLite restore) regularly exceed that and surface as "container is not listening" errors.
const PORT_READY_TIMEOUT_MS = 180_000;
const EDGE_HEALTH_PATH = "/__cfdeploy/health";

function containerEnv(env: Env): Record<string, string> {
  const out: Record<string, string> = {};
  for (const key of (env.CONTAINER_ENV_KEYS || "").split(",").map((k) => k.trim()).filter(Boolean)) {
    const value = env[key];
    if (typeof value === "string") out[key] = value;
  }
  return out;
}

export class Backend extends Container<Env> {
  constructor(ctx: DurableObjectState<{}>, env: Env) {
    // Secrets/vars are read when the container STARTS. A running container keeps its old
    // values until it restarts — cfdeploy always rolls the container on deploy for that reason.
    super(ctx, env, {
      defaultPort: Number(env.CONTAINER_PORT || 8000),
      sleepAfter: env.SLEEP_AFTER || "30m",
      envVars: containerEnv(env),
      enableInternet: true,
    });
  }

  override async fetch(request: Request): Promise<Response> {
    await this.startAndWaitForPorts({ cancellationOptions: { portReadyTimeoutMS: PORT_READY_TIMEOUT_MS } });
    return super.fetch(request);
  }

  override onStart() {
    console.log(JSON.stringify({ event: "container_started" }));
  }

  override onStop(params: { exitCode: number; reason: string }) {
    console.log(JSON.stringify({ event: "container_stopped", ...params }));
  }

  override onError(error: unknown) {
    console.error(JSON.stringify({ event: "container_error", error: String(error) }));
    throw error;
  }
}

async function backendStub(env: Env) {
  const instances = Number(env.INSTANCES || 1);
  if (instances > 1) return getRandom(env.BACKEND, instances); // stateless apps only
  // Singleton. locationHint only applies the first time an instance is created, so the region
  // is part of the name: changing REGION deliberately creates a fresh instance in the new place.
  const id = env.BACKEND.idFromName(`singleton-${env.REGION || "auto"}`);
  return env.BACKEND.get(id, env.REGION ? { locationHint: env.REGION as DurableObjectLocationHint } : undefined);
}

function allowedOrigin(request: Request, env: Env): string | null {
  const origin = request.headers.get("Origin");
  if (!origin) return null;
  const allowed = (env.FRONTEND_ORIGINS || "").split(",").map((o) => o.trim()).filter(Boolean);
  return allowed.includes(origin) ? origin : null;
}

function corsHeaders(origin: string): Record<string, string> {
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Credentials": "true",
    "Access-Control-Expose-Headers": "Content-Disposition, ETag",
    Vary: "Origin",
  };
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const origin = allowedOrigin(request, env);

    // Worker-only liveness check: proves DNS, TLS and the Worker are up without waking the container.
    if (url.pathname === EDGE_HEALTH_PATH) {
      return Response.json({ ok: true, stage: env.APP_STAGE }, { headers: origin ? corsHeaders(origin) : {} });
    }

    // Answer CORS preflights at the edge. A sleeping container would otherwise make the
    // preflight slow or fail, and the browser reports that as a confusing CORS error.
    if (request.method === "OPTIONS" && request.headers.has("Access-Control-Request-Method")) {
      if (!origin) return new Response(null, { status: 403 });
      return new Response(null, {
        status: 204,
        headers: {
          ...corsHeaders(origin),
          "Access-Control-Allow-Methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS",
          "Access-Control-Allow-Headers": request.headers.get("Access-Control-Request-Headers") || "*",
          "Access-Control-Max-Age": "86400",
        },
      });
    }

    let response: Response;
    try {
      const stub = await backendStub(env);
      response = await stub.fetch(request);
    } catch (error) {
      console.error(JSON.stringify({ event: "proxy_error", path: url.pathname, error: String(error) }));
      return Response.json(
        { detail: "Backend is starting or unavailable — please retry shortly." },
        { status: 503, headers: { "Retry-After": "10", ...(origin ? corsHeaders(origin) : {}) } }
      );
    }

    // Platform-generated errors (cold start, max instances, crashes) carry no CORS headers;
    // add them so the frontend sees the real status instead of a CORS failure.
    if (origin && response.status !== 101 && !response.headers.has("Access-Control-Allow-Origin")) {
      response = new Response(response.body, response);
      for (const [k, v] of Object.entries(corsHeaders(origin))) response.headers.set(k, v);
    }
    return response;
  },
} satisfies ExportedHandler<Env>;
